package AgendaCORBA;

/**
* AgendaCORBA/AgendaInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Thursday, September 15, 2016 7:49:22 PM BRT
*/

public final class AgendaInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public AgendaCORBA.AgendaInterface value = null;

  public AgendaInterfaceHolder ()
  {
  }

  public AgendaInterfaceHolder (AgendaCORBA.AgendaInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AgendaCORBA.AgendaInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AgendaCORBA.AgendaInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AgendaCORBA.AgendaInterfaceHelper.type ();
  }

}
