package AgendaCORBA;


/**
* AgendaCORBA/AgendaInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Thursday, September 15, 2016 7:49:22 PM BRT
*/

abstract public class AgendaInterfaceHelper
{
  private static String  _id = "IDL:AgendaCORBA/AgendaInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, AgendaCORBA.AgendaInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AgendaCORBA.AgendaInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AgendaCORBA.AgendaInterfaceHelper.id (), "AgendaInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AgendaCORBA.AgendaInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AgendaInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AgendaCORBA.AgendaInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AgendaCORBA.AgendaInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AgendaCORBA.AgendaInterface)
      return (AgendaCORBA.AgendaInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AgendaCORBA._AgendaInterfaceStub stub = new AgendaCORBA._AgendaInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AgendaCORBA.AgendaInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AgendaCORBA.AgendaInterface)
      return (AgendaCORBA.AgendaInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AgendaCORBA._AgendaInterfaceStub stub = new AgendaCORBA._AgendaInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
