package AgendaCORBA;


/**
* AgendaCORBA/AgendaInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Thursday, September 15, 2016 7:49:22 PM BRT
*/

public interface AgendaInterface extends AgendaInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgendaInterface
