package AgendaCORBA;


/**
* AgendaCORBA/AgendaInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Thursday, September 15, 2016 7:49:22 PM BRT
*/

public interface AgendaInterfaceOperations 
{
  String[] getListContacts ();
  void setListContacts (String[] list);
  String isAlive ();
  void insert (String name, int number);
  void remove (int index);
  int search (String name);
  void update (int index, String name, int number);
} // interface AgendaInterfaceOperations
