package AgendaCORBA;


/**
* AgendaCORBA/listContactsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Thursday, September 15, 2016 7:49:22 PM BRT
*/

public final class listContactsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public listContactsHolder ()
  {
  }

  public listContactsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AgendaCORBA.listContactsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AgendaCORBA.listContactsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AgendaCORBA.listContactsHelper.type ();
  }

}
